"""Initial models

Revision ID: 9f9b9860020f
Revises: 0c8bfe475168
Create Date: 2025-10-24 11:33:43.166923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f9b9860020f'
down_revision = '0c8bfe475168'
branch_labels = None
depends_on = None


def upgrade():
    # NOTE: this migration originally attempted to DROP tables/indexes during upgrade
    # which causes failures when those indexes/tables don't exist. Make the upgrade
    # a no-op so applying the migration won't attempt destructive operations.
    # If you need schema changes, create a new migration instead.
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.ENUM('student', 'teacher', 'admin'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    op.create_table('topics',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('lesson_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data_json', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('topics_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_created_at'), ['created_at'], unique=False)

    op.create_table('progress',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('lesson_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('time_spent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('answers', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('attempt_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('progress_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('progress_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_user_lesson'), ['user_id', 'lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('courses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_created_at'), ['created_at'], unique=False)

    op.create_table('lessons',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content_json', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('content_version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('lessons_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_course_id'), ['course_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('uploader_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mime_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('assets_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_uploader_id'), ['uploader_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
